project:
  type: website

website:
  title: "The Data Enthusiast Blog"
  favicon: favicon.png
  page-footer:
    center: ""
    left:
      "Made with [Posit Quarto](https://quarto.org/)"
    right: ""
    background: "#1B4132"
  navbar:
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "Resume"
        file: Gallihugh_Resume.pdf
      - text: "Academic CV"
        file: CV.pdf
      - text: "Data Visualization Projects"
        file: tidytuesday.qmd
      - text: "Data Portfolio"
        file: projects.qmd
      - text: "Presentations"
        menu:
        - text: "MPA 2021"
          href: MPA2021_Poster.pdf
        - text: "MPA 2023"
          href: Gallihugh_MPA_2023.pdf
        - text: "OU Department Brown Bag Talk"
          href: Brown_Bag_BLM_March_25.pdf
        - text: "SPSP 2021"
          href: SPSP2021_Poster.pdf
        - text: "SPSP 2022"
          href: SPSS_Poster.pdf
        - text: "SPSP 2023"
          href: MarleyConfPresentation.html
      - icon: github
        href: https://github.com/bsgallih12
      - icon: twitter
        href: https://twitter.com/Brier_Gallihugh
      - icon: linkedin
        href: https://linkedin.com/in/brier-gallihugh
      - icon: envelope
        text: "Email"
        href: mailto:bg464219@ohio.edu
format:
  html:
    theme: custom_dark.scss
    code-link: true
    code-fold: false
    


