project:
  type: website

website:
  title: "The R Nerd Blog"
  navbar:
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "Tidy Tuesday Projects"
        file: tidytuesday.qmd
      - text: "Projects"
        file: projects.qmd
      - icon: github
        href: https://github.com/bsgallih12
      - icon: twitter
        href: https://twitter.com/Brier_Gallihugh
      - icon: linkedin
        href: https://linkedin.com/in/brier-gallihugh
format:
  html:
    theme: 
      light: [custom.scss]
      dark: [custom.scss,light_custom.scss]
    code-link: true
    code-fold: show
    


