---
links:
  - icon: twitter
    text: Twitter
    href: https://twitter.com
  - icon: linkedin
    text: LinkedIn
    href: https://linkedin.com
  - icon: github
    text: Github
    href: https://github.com\
theme: Resume.scss
---

[Brier Gallihugh, M.S.]{.center-twenty}\
[Data Analysis \| UXR \| Data Science]{.center-twenty}

[Personal Summary]{.left-header}

I am a third year experimental psychology doctoral candidate at Ohio University. I bring over 5 years of detail oriented experience using various quantitative research methodologies (e.g., experimental design and survey development) and conducting various statistical analyses (e.g., ANOVA, regression, moderation and mediation, meta-analysis, factor analysis, structural equation modeling, etc.) to understand human behavior. Further I also have some experience with semi-structured interviewing. I am proficient in the use of both SPSS and R for data analysis and ggplot2 for data visualization.

Relevant Soft Skills

• Communication

• Collaboration

• Project Management

• Oral Presentation

[Experience]{.left-header}

[Principle Psychology Researcher]{.left-subheader} [August 2020-Present]{.right-subheader} <br> <br> [Ohio University]{.left-subheadernofloat} <br> <br> • Designed, developed and administered studies pertaining to insights regarding psychological topics of human behavior including prejudice, discrimination, and attitudes as they related to racial, ethnic and religious minorities in addition to political affiliation

• Cleaned and analyzed data using statistical procedures including ANOVA, t-tests, regression, multiple regression, moderation, mediation, and sentiment analysis using R statistical software with the RStudio IDE

• Incorporated version control for statistical analyses using Git and GitHub to ensure data reproducibility

• Research resulted in 13 research studies across 6 projects resulting in a conference poster, departmental talk, and a manuscript currently in progress

• Collaborated with other researchers to analyze data and parse out insights regarding human morality

[Instructor of Record]{.left-subheader} [January 2022-Present]{.right-subheader} <br> <br> [Ohio University]{.left-subheadernofloat} <br>

• Taught courses on social psychology

• Designed slide decks and presented course content via lecture format related to social cognition, the self, prejudice and discrimination, research design, etc. to 90 students across 2 semesters

• Assessed students on their course knowledge by designing 4 tests, 10 quizzes, and requiring a written final paper to demonstrate critical thinking and reflection

• Student evaluations indicated a high degree overall quality for both the instructor \[4.58/5.0\] and the course \[4.31/5.0\].

[Principle Psychology Researcher]{.left-subheader} [August 2017-August 2021]{.right-subheader} <br> <br> [Eastern Michigan University]{.left-subheadernofloat} <br> <br> • Designed, developed and administered studies pertaining to insights regarding psychological topics involving prejudice and attitudes as they related to racial and religious minorities in addition to voting behavior involving sexual misconduct allegations

• Cleaned and analyzed data using statistical procedures including ANOVA, t-tests, correlation, mediation, exploratory factor analysis using R statistical software with the RStudio IDE

• Research resulted in 5 studies across 4 projects resulting in a 3 conference posters, a master's thesis proposal, and thesis defense

[Selected Projects]{.left-header}

[Black Lives Matter]{.left-subheader} <br>

• This research looked to investigate the role that multicultural attitudes (i.e., celebration of differences) and colorblind attitudes (i.e., avoiding differences) play in predicting support for Black Lives Matter (and All Lives Matter) using a series of multiple regressions and experimental manipulations. The results largely indicate that support for Black Lives Matter is positive associated with endorsement of multicultural attitudes and negatively associated with endorsement of colorblind attitudes. By comparison, All Lives Matter support is positively associated with endorsement of colorblind attitudes and negatively associated with endorsement of multicultural attitudes. This work suggests that organizations who wish to increase support for Black Lives Matter would be wise to focus on interventions which increase one's positive attitudes toward a multicultural society.

• This research has resulted in one departmental talk and one research manuscript

[The Marley Hypothesis: A Gender Extension]{.left-subheader} <br>

• This research looked to investigate the role of historical literacy (with respect to women's rights) on the relationship between gender and willingness to identify a situation as sexist using a series of mediation analyses. The results largely indicate that historical literacy does not impact the relationship between gender and willingness to identify a situation as sexist.

• This research has resulted in a proposed conference poster presentation. The poster can be found here

[Christian Privilege Awareness]{.left-subheader} <br>

• This research looked to create a scale measure to assess the level of Christian privilege awareness among self-professed Christians through the use of scale development principles (i.e., theory development) and statistical analysis (e.g., exploratory factor analysis). The results largely indicate a good measure of Christian privilege awareness with a high degree of internal reliability.

• This research was my master's thesis final project and resulted in a conference poster presentation

[Skills]{.left-header}

[Statistical Procedure Experience]{.left-subheader} <br>

-   Regression

-   ANOVA

-   ANCOVA

-   EFA & CFA

-   Mediation & Moderation

-   SEM

-   Meta-Analysis

[Statistical Software and Visualizations]{.left-subheader} <br>

-   R & RStudio

-   SPSS

-   G\*Power

-   ggplot2

[Other Software]{.left-subheader} <br>

-   Qualtrics

-   Office Suite

-   Google Suite

-   Git & GitHub

[Education]{.left-header}

[Ohio University]{.left-subheader} [August 2020-Present]{.right-subheader} <br>

Doctorate of Philosophy (Ph.D) in Experimental Psychology

Concentration: Social Psychology (4.00 GPA)

Expected Graduation: May 2025

<br>

[Eastern Michigan University]{.left-subheader} [August 2017-August 2021]{.right-subheader} <br>

Master of Science (M.S) in General Experimental Psychology

<br>

[Saginaw Valley State University]{.left-subheader} [August 2012-May 2017]{.right-subheader} <br>

Bachelor of Arts (B.A) in Psychology

Minor: Biology
